[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
DEFMT_LOG="info"
ESP_LOG="INFO"

[build]
target = "riscv32imc-unknown-none-elf"
rustflags = [
    # Required
    "-C", "link-arg=-Tlinkall.x",
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    "-C", "force-frame-pointers",

    # Uncomment when enabling defmt
    # "-C", "link-arg=-Tdefmt.x",

    # Uncomment for esp32c6 and esp32h2
    # "-C", "link-arg=-Trom_coexist.x",
    # "-C", "link-arg=-Trom_phy.x",
]

[unstable]
build-std = ["alloc", "core"]

